# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajumpingapedjango', '0004_newuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajumpingapedjango.NewUser'),
        ),
    ]
