# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajumpingapedjango', '0005_auto_20160521_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerHorizontalSpeed', models.FloatField(default=0.0)),
                ('brainSpawDeltaY', models.FloatField(default=0.0)),
                ('bananaSpawDeltaY', models.FloatField(default=0.0)),
                ('jumpForce', models.FloatField(default=0.0)),
                ('startJumpForce', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Game Balance',
                'verbose_name_plural': 'Game Balance',
            },
        ),
    ]
